### ISSUE TITLE
Zennでのアカウント作成時の500エラーについて

### ISSUE THREAD

**Issue by DJStompZone** [zenn-dev/zenn-community#609]
### 事象

アカウントを作成しようとしていますが、問題が発生しました。Googleでサインインし、ユーザー名と表示名を選んだ後、送信すると「500 エラーが発生しました」というページに遷移します。エラーが表示されるURLは[https://zenn.dev/auth/init?redirect_to=%2Fmae616%2Fscraps%2F9400aeaeff9493](https://zenn.dev/auth/init?redirect_to=%2Fmae616%2Fscraps%2F9400aeaeff9493)です。

この問題は、Edge Desktop、Chrome Desktop、Chrome Mobileで複数のGoogleアカウントを使ってサインアップしようとしても同様です。ユーザー名は有効で、既に取られていないことを確認しました。コンソールでは以下のエラーが表示されています：

```
framework-ca706bf673a13738.js:9
 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Xj (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:89747)
    at fk (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:89874)
    at ek (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86746)
    at dk (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86430)
    at ek (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86543)
    at dk (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86430)
    at ek (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86738)
    at dk (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86430)
    at ek (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86543)
    at dk (https://static.zenn.studio/_next/static/chunks/framework-ca706bf673a13738.js:9:86430)
```

お手数をおかけして申し訳ありませんが、この問題について調査していただけますか？

どうぞよろしくお願いいたします。心から、

<img width="30%" src="https://github.com/zenn-dev/zenn-community/assets/85457381/0993987e-a837-438f-904a-205edb6446c5">

[DJ](mailto:dj@deepai.org)
[DeepAI.org](https://deepai.org)

また、日本語が母国語ではないため、言葉遣いに不備があればお許しください。

### 発生したページのURL

https://zenn.dev/auth/init?redirect_to=%2Fmae616%2Fscraps%2F9400aeaeff9493

### 発生した画面のスクリーンショット

![image](https://github.com/zenn-dev/zenn-community/assets/85457381/a13645ae-6211-4ffc-8ff9-083a4eea21cc)
![image](https://github.com/zenn-dev/zenn-community/assets/85457381/9594e7cf-da04-46c3-a27e-3770af4ba3fa)

### 再現方法

手順は上で説明されています

### Android 14 (Google Pixel 6A)
- Google Chrome モバイル
     バージョン 121.0.6167.178

### デスクトップ - MacOS Sonoma (ARM 搭載 MacBook Air)
- Google Chrome デスクトップ (MacOS)
     バージョン 124.0.6367.119 (公式ビルド) (arm64)
- Microsoft Edge デスクトップ (MacOS)
     バージョン 124.0.2478.80 (公式ビルド) (arm64)

**Comment by cm-igarashi-ryosuke** [comment]
@DJStompZone こんにちは。こちらの問題について調査をしていますが、今のところ手がかりがつかめません。追加で以下の情報をいただけますでしょうか。

- エラーが発生するのは「Proceed to the next →」ボタンを押した直後ですか？
- エラーが発生したとき、ネットワーク通信・エラーは発生していますか？
- 全ての環境で共通して使われているブラウザ拡張はありますか？

**Comment by cm-igarashi-ryosuke** [comment]
しばらくレスポンスがないためクローズいたします。

また何かありましたらコメントいただければと思います。
