### ISSUE TITLE
[CLI] Frontmatter に文法エラーがある記事が存在する場合の preview およびコマンド出力の問題

### ISSUE THREAD

**Issue by sankantsu** [zenn-dev/zenn-community#658]
### 事象

記事の yaml frontmatter (記事メタデータ) に文法エラーがある記事が存在するとき、CLI の動作について以下の問題があります。

- `zenn preview` によるプレビュー画面で記事が表示できなくなる。
- `zenn list:articles` コマンドで長大なエラー (281 万文字) が出力されてクラッシュする。

Frontmatter に文法エラーがある記事が存在する場合について、一例として以下のような動きが望ましいと考えます。

- `zenn preview`
  - frontmatter に文法エラーがない記事
    - 画面左部の記事一覧および記事プレビューともに通常通り表示する。
  - frontmatter に文法エラーがある記事
    - 画面左部の記事一覧および記事プレビュー最上部のタイトル表示位置に代替タイトル (e.g. 固定の警告文字列 または 本文先頭から取得した文字列など) を表示する。
      - frontmatter からタイトルが取得できないと想定されるため代替タイトルを想定した。
      - タイトルが取得可能であれば (警告付きで) タイトルを表示しても良い。
    - 可能であれば frontmatter の文法エラーについて記事プレビュー画面上に表示する。
    - 可能であれば本文は frontmatter にエラーがない場合と同様にそのまま表示する。
- `zenn list:articles`
  - frontmatter に文法エラーがある記事が存在する場合、warning を出力してスキップする。
    - または frontmatter が部分的に解析できる場合、解析できた部分のみを含む不完全な出力を含めても良い。
  - 文法エラーが存在しない記事については、通常通り一覧に含めて出力する。

補足情報: 自作の Zenn 記事編集用の [エディタプラグイン](https://github.com/sankantsu/telescope-zenn.nvim) 使用中、frontmatter のエラー (e.g. タイトルの quote 閉じ忘れ) があるときに記事一覧が取得できないことから問題に気がつきました。プラグインでの応用の都合から言えば、特定の記事にエラーが存在しても `list:articles` でできる限り完全に近い形の記事リストを取得できると嬉しいです。

### 発生したページのURL

ローカル環境上での編集中の記事のみ (Frontmatter にエラーがある場合、正常な記事としてアップロードできないため)

### 発生した画面のスクリーンショット

- `zenn preview`

記事編集中に frontmatter にエラーを発生させた後、該当の記事を再読み込みした場合

<img width="1582" alt="Screenshot 2024-11-29 21 48 57" src="https://github.com/user-attachments/assets/13754b23-ba26-4c94-b1ad-5117b10695ca">

すでに frontmatter にエラーがある記事が存在する状態で新しく `zenn preview` を起動した場合

<img width="1582" alt="Screenshot 2024-11-29 21 52 42" src="https://github.com/user-attachments/assets/927062f1-cd3e-437b-9a1c-4729e60f144b">

- `zenn list:articles`

非常に長大なエラーが出力されます (281 万文字)。

```
~/blog/zenn% npx zenn list:articles 2>&1 | wc -c
 2813909
```

```
(node:16692) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js
 is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16714) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative i
nstead.
(Use `node --trace-deprecation ...` to show where the warning was created)

/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3
(()=>{var __webpack_modules__={44900:(e,t)=>{"use strict";function n(e,t,n){var a,r=t,i={ok:!1,pos:t,value:""};for(
a=e.charCodeAt(t);t<n&&a>=48&&a<=57||37===a;)a=e.charCodeAt(++t);return i.ok=!0,i.pos=t,i.value=e.slice(r,t),i}Obje
ct.defineProperty(t,"__esModule",{value:!0}),t.parseImageSize=void 0,t.parseImageSize=function(e,t,a){var r=e.charC
odeAt(t),i={ok:!1,pos:0,width:"",height:""};if(t>=a)return i;if(61!==r)return i;if(t++,120!==(r=e.charCodeAt(t))&&(
r<48||r>57))return i;var s=n(e,t,a);if(t=s.pos,120!==(r=e.charCodeAt(t)))return i;var o=n(e,++t,a);return t=o.pos,i
.width=s.value,i.height=o.value,i.pos=t,i.ok=!0,i}},57405:(e,t,n)=>{"use strict";Object.defineProperty(t,"__esModul
e",{value:!0});var a=n(44900);t.default=function(e){e.inline.ruler.before("emphasis","image",function(e){return fun
ction(t,n){var r,i,s,o,l,c,p,u,d,m,h,f,g="",E="",b="",_=t.pos,D=t.posMax;if(33!==t.src.charCodeAt(t.pos))return!1;i
f(91!==t.src.charCodeAt(t.pos+1))return!1;if(l=t.pos+2,(o=e.helpers.parseLinkLabel(t,t.pos+1,!1))<0)return!1;if((c=
o+1)<D&&40===t.src.charCodeAt(c)){for(c++;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);if(c>=D)return!1;for(f=c
,(u=e.helpers.parseLinkDestination(t.src,c,t.posMax)).ok&&(b=t.md.normalizeLink(u.str),t.md.validateLink(b)?c=u.pos
:b=""),f=c;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);if(u=e.helpers.parseLinkTitle(t.src,c,t.posMax),c<D&&f!
==c&&u.ok)for(d=u.str,c=u.pos;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);else d="";if(c-1>=0&&32===(i=t.src.c
harCodeAt(c-1))&&(u=a.parseImageSize(t.src,c,t.posMax)).ok)for(g=u.width,E=u.height,c=u.pos;c<D&&(32===(i=t.src.cha
rCodeAt(c))||10===i);c++);if(c>=D||41!==t.src.charCodeAt(c))return t.pos=_,!1;c++}else{if(void 0===t.env.references
)return!1;for(;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);if(c<D&&91===t.src.charCodeAt(c)?(f=c+1,(c=e.helper
s.parseLinkLabel(t,c))>=0?s=t.src.slice(f,c++):c=o+1):c=o+1,s||(s=t.src.slice(l,o)),!(p=t.env.references[e.utils.no
rmalizeReference(s)]))return t.pos=_,!1;b=p.href,d=p.title}if(!n){t.pos=l,t.posMax=o;var v=new t.md.inline.State(t.
src.slice(l,o),t.md,t.env,h=[]);v.md.inline.tokenize(v),(m=t.push("image","img",0)).attrs=r=[["src",b],["alt",""]],
(略)
YAMLException: missed comma between flow collection entries (6:1)

 3 | emoji: "⚙️"
 4 | type: "tech"
 5 | topics: ["Neovim", "LSP"
 6 | published: true
-----^
 7 | published_at: 2023-12-11
 8 | publication_name: vim_jp
    at Du (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2600423)
    at vu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2600458)
    at /Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2608417
    at Lu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2609013)
    at /Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2607611
    at Lu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2607935)
    at Pu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2615303)
    at Fu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2616047)
    at Object.load (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2616272)
    at Object.yaml [as parse] (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2626261) {
  reason: 'missed comma between flow collection entries',
  mark: {
    name: null,
    buffer: '\n' +
      'title: "Neovim の LSP を設定するための基本知識"\n' +
      'emoji: "⚙️"\n' +
      'type: "tech"\n' +
      'topics: ["Neovim", "LSP"\n' +
      'published: true\n' +
      'published_at: 2023-12-11\n' +
      'publication_name: vim_jp\n',
    position: 86,
    line: 5,
    column: 0,
    snippet: ' 3 | emoji: "⚙️"\n' +
      ' 4 | type: "tech"\n' +
      ' 5 | topics: ["Neovim", "LSP"\n' +
      ' 6 | published: true\n' +
      '-----^\n' +
      ' 7 | published_at: 2023-12-11\n' +
      ' 8 | publication_name: vim_jp'
  }
}

Node.js v23.1.0
```

### 再現方法

Frontmatter 部分に文法エラーを発生させることで再現します。

- 例1: `title` の quote を閉じていない

```yaml
---
title: "Neovim の LSP を設定するための基本知識
emoji: "⚙️"
type: "tech"
topics: ["Neovim", "LSP"]
published: true
published_at: 2023-12-11
publication_name: vim_jp
---
```

- 例2: `topics` のリストを閉じていない

```yaml
---
title: "Neovim の LSP を設定するための基本知識"
emoji: "⚙️"
type: "tech"
topics: ["Neovim", "LSP"
published: true
published_at: 2023-12-11
publication_name: vim_jp
---
```

### 環境

- MacOS: 13.7
- Node.js: v23.1.0
- zenn-cli: 0.1.158

**Comment by cm-wada-yusuke** [comment]
@sankantsu 詳細にありがとうございます。お手数おかけして申し訳ないです。

> 特定の記事にエラーが存在しても list:articles でできる限り完全に近い形の記事リストを取得できると嬉しいです。

こちらの方向で影響を極小化するように考えてみます。
